### ISSUE TITLE
Test Code 

### ISSUE THREAD

**Issue by mwhite192** [mwhite192/Web-Developer-P6#3]
@AccessiT3ch - Hey Conor!  I have a unique request.  Can you test my code please and thank you?  I have tested and it seems okay to me, but something seems funny whenever it comes to the likes and dislikes.  I feel as though those counts are changing whenever the user changes for some reason.  For example, when I log in, the count for sauce's like and dislike is 1 and 1 which is how I originally tested the counts using two different users.  Then I log in with another user, I add a like and the count then goes to 2 likes and 1 dislike; however, when I log in as the original user, the counts might then be 3 likes and 0 dislike (or something other than 2 likes and 1 dislike) even though I didn't like or dislike anything.  It could be just me because I was testing so much.  I just feel another pair of eyes might help! :)

**Comment by AccessiT3ch** [comment]
@mwhite192 will do! I'll take a look today :)

**Comment by AccessiT3ch** [comment]
@mwhite192 This all looks great, there's just one quick think and then I think you'll be good to go!

When I first installed and ran the code, I was getting a cryptic 500 error when adding my first sauce, TLDR: Multer was freaking out bc there wasn't an `images` folder to put the images.

<img width="1233" alt="Screenshot 2023-03-20 at 11 13 19 AM" src="https://user-images.githubusercontent.com/95449364/226431431-1fb78cae-471c-4790-bd7d-bdd032b29695.png">

### The Fix
1. Commit a file in the `images` folder so that git can realize there's a folder there, basically git can't track empty folders, it's just tracking the files, so the only way to force this folder to exist upon installation is to include a file (an image probably!)

2. Multer is erroring out in a way that is both not very informative AND is causing a typeError in the front-end (b/c the response doesn't include a `message`.  There really doesn't seem to be much good documentation on how to handle errors with Multer... I found some [comments declaring that Multer would attempt to create the directory](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/multer/index.d.ts#L278-L292), but clearly it's failing to do so. [This was the best example](https://gist.github.com/huynhsamha/348722d47ee457454688698ff77fee1a) I could find of custom error handling for Multer, but they're not really using it as middleware... I think at this point we should just go with the first fix and call it good for now!

**Comment by AccessiT3ch** [comment]
@mwhite192 Ok because I couldn't let it go, this is how one might write a custom middleware function to call the multer instance with an actual error callback to handle errors!

![Screenshot 2023-03-20 at 11 59 13 AM](https://user-images.githubusercontent.com/95449364/226440033-88fcfff5-53b6-431c-832c-e000d7a53f50.png)

Strangely enough, sometimes Multer would be able to create the `images` folder, I could determine a pattern so I think our best bet is definitely to make sure that directory has a file that's checked into github :)

**Comment by mwhite192** [comment]
@AccessiT3ch  - My apologies for the delayed response to this ticket.  Work last week was rough and I needed the weekend to recoup.  I will just create a sauce that will sit in the database.  That should also save an image in the image directory.  Once I do that, I will resave the project to GitHub.  I just want to make sure.......that's the only thing we need to do correct?  I SHOULD NOT implement the code snippets you provided relating to Multer.......right?

**Comment by AccessiT3ch** [comment]
@mwhite192 - Yup that's it, no need to mess with your multer config at this point :)

**Comment by mwhite192** [comment]
@AccessiT3ch - Done and Done!
